[package]
name = "reev-agent"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
axum = "0.8.4"
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
regex = { workspace = true }
solana-sdk = { workspace = true }
bs58 = { workspace = true }
reev-lib = { path = "../reev-lib" }
anyhow = { workspace = true }
solana-system-interface = { workspace = true }
spl-token = { workspace = true }
serde_yaml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dotenvy = "0.15"

# Correct rig dependencies
rig-core = { version = "0.20.0" }
async-trait = "0.1"
thiserror = "1.0"

jupiter-swap-api-client = { git = "https://github.com/jup-ag/jupiter-swap-api-client.git", package = "jupiter-swap-api-client"}
solana-client.workspace = true
reqwest = "0.12"
hex = "0.4.3"
chrono = "0.4.42"
spl-associated-token-account.workspace = true

[dev-dependencies]
reqwest = { version = "0.12", features = ["json"] }
serde_yaml = "0.9"
tracing-subscriber = "0.3"
solana-sdk = { workspace = true }
clap = { version = "4.5", features = ["derive"] }
