[package]
name = "reev-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
reev-lib = { path = "../reev-lib" }
anyhow = "1.0"
serde_yaml = "0.9"
serde_json = "1.0"
clap = { version = "4.5.4", features = ["derive"] }
