[package]
name = "reev-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
reev-lib = { path = "../reev-lib" }
anyhow = "1.0"
serde_yaml = "0.9"
serde_json = "1.0"
clap = { version = "4.5.4", features = ["derive"] }

# Observability
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "registry"] }
tracing-opentelemetry = "0.23.0"
opentelemetry = "0.22.0"
opentelemetry_sdk = { version = "0.22.1", features = ["rt-tokio"] }
opentelemetry-stdout = { version = "0.3.0", features = ["trace"] }
