[package]
name = "turso-test"
version = "0.1.0"
edition = "2021"

[workspace]

[[bin]]
name = "simple_test"
path = "src/simple_test.rs"

[[bin]]
name = "debug_upsert"
path = "debug_upsert.rs"

[[bin]]
name = "step6_reproduce_original_issue"
path = "step_by_step/tests/step6_reproduce_original_issue.rs"

[[bin]]
name = "turso_upsert_concurrency_test"
path = "step_by_step/tests/turso_upsert_concurrency_test.rs"

[[bin]]
name = "inspect_db"
path = "inspect_db.rs"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
turso = "0.1.5"
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
md5 = "0.7"
