[package]
name = "turso-test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "simple_test"
path = "src/simple_test.rs"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
turso = "0.1.5"
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
