[package]
name = "reev-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
hex = "0.4"
base64 = "0.21"

# Solana Dependencies
solana-client = "1.18.11"
solana-program = "1.18.11"
solana-sdk = "1.18.11"
spl-token = { version = "4.0.0", features = ["no-entrypoint"] }
