[package]
name = "reev-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
hex = "0.4"
base64 = "0.21"
bs58 = "0.5.1"
tracing = "0.1"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
regex = "1"


# Solana Dependencies
solana-client = { workspace = true }
solana-sdk = { workspace = true }
spl-associated-token-account = "7.0.0"
spl-token = { workspace = true, features = ["no-entrypoint"] }
solana-program = "2.3.0"
solana-system-transaction = "2.2.1"
solana-system-interface = "1.0.0"
