stateDiagram-v2
    [*] --> StartAgent

    state "Execution1" as Execution1
        Execution1
            [*] --> AgentStart
            state "Agent Start\nModel: unknown_agent" as AgentStart
            state "AccountBalanceTool" as Tool1
            AgentStart --> Tool1
            state "JupiterSwapTool" as Tool2
            Tool1 --> Tool2
            state "Agent End" as AgentEnd
            Tool2 --> AgentEnd

    Execution1 --> [*]

    classDef Other0 fill:#ff6b6b
    classDef Other1 fill:#ff6b6b
    class OtherAccountBalanceTool Other
    class OtherJupiterSwapTool Other
